import type { Category, City, User } from '@/shared/types'
import type { CatalogPageProps } from './CatalogPage'

export const catalogCategories: Category[] = [
  {
    id: 'business-career',
    name: 'Бизнес и карьера',
    subcategories: [
      { id: 'team-management', name: 'Управление командой' },
      { id: 'marketing-advertising', name: 'Маркетинг и реклама' },
      { id: 'sales-negotiations', name: 'Продажи и переговоры' },
      { id: 'personal-brand', name: 'Личный бренд' },
      { id: 'resume-interview', name: 'Резюме и собеседование' },
      { id: 'time-management', name: 'Тайм-менеджмент' },
      { id: 'project-management', name: 'Проектное управление' },
      { id: 'entrepreneurship', name: 'Предпринимательство' },
    ],
  },
  {
    id: 'foreign-languages',
    name: 'Иностранные языки',
    subcategories: [
      { id: 'english', name: 'Английский' },
      { id: 'french', name: 'Французский' },
      { id: 'spanish', name: 'Испанский' },
      { id: 'german', name: 'Немецкий' },
    ],
  },
  {
    id: 'home-comfort',
    name: 'Дом и уют',
    subcategories: [
      { id: 'cleaning-organization', name: 'Уборка и организация' },
      { id: 'home-finance', name: 'Домашние финансы' },
      { id: 'cooking', name: 'Приготовление еды' },
      { id: 'houseplants', name: 'Домашние растения' },
    ],
  },
  {
    id: 'creativity-art',
    name: 'Творчество и искусство',
    subcategories: [
      { id: 'drawing-illustration', name: 'Рисование и иллюстрация' },
      { id: 'photography', name: 'Фотография' },
      { id: 'video-editing', name: 'Видеомонтаж' },
      { id: 'music-sound', name: 'Музыка и звук' },
    ],
  },
  {
    id: 'education-development',
    name: 'Образование и развитие',
    subcategories: [
      { id: 'personal-development', name: 'Личностное развитие' },
      { id: 'learning-skills', name: 'Навыки обучения' },
      { id: 'cognitive-techniques', name: 'Когнитивные техники' },
      { id: 'speed-reading', name: 'Скорочтение' },
    ],
  },
  {
    id: 'health-lifestyle',
    name: 'Здоровье и лайфстайл',
    subcategories: [
      { id: 'yoga-meditation', name: 'Йога и медитация' },
      { id: 'nutrition-wellness', name: 'Питание и ЗОЖ' },
      { id: 'mental-health', name: 'Ментальное здоровье' },
      { id: 'mindfulness', name: 'Осознанность' },
    ],
  },
]

export const catalogCities: City[] = [
  { id: 'moscow', name: 'Москва' },
  { id: 'saint-petersburg', name: 'Санкт-Петербург' },
  { id: 'novosibirsk', name: 'Новосибирск' },
  { id: 'yekaterinburg', name: 'Екатеринбург' },
  { id: 'kazan', name: 'Казань' },
  { id: 'rostov-on-don', name: 'Ростов-на-Дону' },
  { id: 'murmansk', name: 'Мурманск' },
  { id: 'noginsk', name: 'Ногинск' },
  { id: 'irkutsk', name: 'Иркутск' },
]

export const catalogUsers: User[] = [
  {
    id: 'user-001',
    name: 'Юлия',
    birthDate: '2002-01-15',
    gender: 'female',
    cityId: 'moscow',
    avatarUrl: '/images/users/user-001/avatar.webp',
    description: 'Люблю делиться знаниями и осваивать новые навыки.',
    offeredSkill: {
      title: 'Управление командой',
      categoryId: 'business-career',
      subcategoryId: 'team-management',
      description: 'Помогу разобраться в основах управления командой.',
      imageUrls: [],
    },
    learningSubcategoryIds: ['time-management', 'yoga-meditation'],
    likesCount: 120,
    createdAt: '2026-07-10T00:00:00.000Z',
  },
  {
    id: 'user-002',
    name: 'Алексей',
    birthDate: '1999-02-12',
    gender: 'male',
    cityId: 'saint-petersburg',
    avatarUrl: '/images/users/user-002/avatar.webp',
    description: 'Интересуюсь развитием команд и обменом опытом.',
    offeredSkill: {
      title: 'Разговорный английский',
      categoryId: 'foreign-languages',
      subcategoryId: 'english',
      description: 'Помогу увереннее говорить и понимать английскую речь.',
      imageUrls: [],
    },
    learningSubcategoryIds: ['photography', 'german'],
    likesCount: 110,
    createdAt: '2026-07-15T00:00:00.000Z',
  },
  {
    id: 'user-003',
    name: 'Альберт',
    birthDate: '1985-03-18',
    gender: 'male',
    cityId: 'saint-petersburg',
    avatarUrl: null,
    description: 'Работаю с рекламой и готов делиться практическим опытом.',
    offeredSkill: {
      title: 'Домашняя кухня',
      categoryId: 'home-comfort',
      subcategoryId: 'cooking',
      description: 'Научу готовить простые блюда из доступных продуктов.',
      imageUrls: [],
    },
    learningSubcategoryIds: ['cooking', 'music-sound'],
    likesCount: 100,
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'user-004',
    name: 'Анастасия',
    birthDate: '2004-04-21',
    gender: 'female',
    cityId: 'novosibirsk',
    avatarUrl: '/images/users/user-004/avatar.webp',
    description: 'Люблю творческие проекты и понятные объяснения.',
    offeredSkill: {
      title: 'Рисование для начинающих',
      categoryId: 'creativity-art',
      subcategoryId: 'drawing-illustration',
      description: 'Помогу освоить основы рисунка и композиции.',
      imageUrls: [],
    },
    learningSubcategoryIds: ['cooking', 'spanish'],
    likesCount: 70,
    createdAt: '2026-08-30T00:00:00.000Z',
  },
  {
    id: 'user-005',
    name: 'Дарья',
    birthDate: '1989-05-25',
    gender: 'female',
    cityId: 'rostov-on-don',
    avatarUrl: '/images/users/user-005/avatar.webp',
    description: 'Ценю практический подход и полезный обмен знаниями.',
    offeredSkill: {
      title: 'Эффективное обучение',
      categoryId: 'education-development',
      subcategoryId: 'learning-skills',
      description: 'Покажу способы организации и запоминания материала.',
      imageUrls: [],
    },
    learningSubcategoryIds: ['home-finance', 'mindfulness'],
    likesCount: 60,
    createdAt: '2026-08-29T00:00:00.000Z',
  },
  {
    id: 'user-006',
    name: 'Олег',
    birthDate: '1979-06-14',
    gender: 'male',
    cityId: 'murmansk',
    avatarUrl: '/images/users/user-006/avatar.webp',
    description: 'Занимаюсь развитием личного бренда.',
    offeredSkill: {
      title: 'Йога для начинающих',
      categoryId: 'health-lifestyle',
      subcategoryId: 'yoga-meditation',
      description: 'Познакомлю с базовыми упражнениями и дыхательными практиками.',
      imageUrls: [],
    },
    learningSubcategoryIds: ['video-editing', 'personal-development'],
    likesCount: 50,
    createdAt: '2026-08-28T00:00:00.000Z',
  },
  {
    id: 'user-007',
    name: 'Михаил',
    birthDate: '1970-07-17',
    gender: 'male',
    cityId: 'noginsk',
    avatarUrl: null,
    description: 'Помогаю готовиться к собеседованиям.',
    offeredSkill: {
      title: 'Резюме и собеседование',
      categoryId: 'business-career',
      subcategoryId: 'resume-interview',
      description: 'Разберём резюме и типичные вопросы работодателей.',
      imageUrls: [],
    },
    learningSubcategoryIds: ['nutrition-wellness', 'french'],
    likesCount: 40,
    createdAt: '2026-06-15T00:00:00.000Z',
  },
  {
    id: 'user-008',
    name: 'Аркадий',
    birthDate: '2003-08-08',
    gender: 'male',
    cityId: 'irkutsk',
    avatarUrl: '/images/users/user-008/avatar.webp',
    description: 'Изучаю способы эффективной организации времени.',
    offeredSkill: {
      title: 'Основы фотографии',
      categoryId: 'creativity-art',
      subcategoryId: 'photography',
      description: 'Расскажу о композиции, свете и базовых настройках камеры.',
      imageUrls: [],
    },
    learningSubcategoryIds: ['german', 'houseplants'],
    likesCount: 30,
    createdAt: '2026-06-10T00:00:00.000Z',
  },
  {
    id: 'user-009',
    name: 'Анна',
    birthDate: '1983-09-01',
    gender: 'female',
    cityId: 'moscow',
    avatarUrl: '/images/users/user-009/avatar.webp',
    description: 'Люблю системный подход к работе над проектами.',
    offeredSkill: {
      title: 'Проектное управление',
      categoryId: 'business-career',
      subcategoryId: 'project-management',
      description: 'Помогу организовать работу над проектом.',
      imageUrls: [],
    },
    learningSubcategoryIds: ['cognitive-techniques', 'yoga-meditation'],
    likesCount: 20,
    createdAt: '2026-06-05T00:00:00.000Z',
  },
]

export const catalogPageMock: CatalogPageProps = {
  users: catalogUsers,
  categories: catalogCategories,
  cities: catalogCities,
  onFavoriteClick: (id) => console.log('Избранное:', id),
  onDetailsClick: (id) => console.log('Подробнее:', id),
}
